### PR TITLE
Update setup version and descriptions

### PR DESCRIPTION
**Pull request by blowekamp**

### CODE REVIEW

**Comment by jcfr** [comment]
With the introduction of `+pythonpackage` what will be the version string for a source distribution ?

**Comment by jcfr** [comment]
Thanks for clarifying

> The addition of +pythonpackage is a suitable for distinguishing this Python source distribution form the main SimpleITK distribution.

Since source distribution can (and should) also be distributed on PyPi, should a normal version scheme be used for them ?

**Comment by blowekamp** [comment]
Apologies to for the confusing error in the previous comment; its now corrected.

The version of the source must be the same as the binary wheels or there would be preference when pip chooses the latest version. And the package name must be SimpleITK too. So I believe there is no alternative but to have the source package be named `SimpleITK-1.0.1.tar.gz`. Any other options?

**Comment by blowekamp** [comment]
Abandoning local version specifier #37

**Pull request closed without merging**
